# Generated by Django 5.1.6 on 2025-03-02 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouping',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.enterprise'),
        ),
        migrations.AddField(
            model_name='grouping_permissions',
            name='grouping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.grouping'),
        ),
        migrations.AddField(
            model_name='grouping_permissions',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission'),
        ),
        migrations.AddField(
            model_name='grouping',
            name='permissions',
            field=models.ManyToManyField(through='accounts.Grouping_Permissions', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='user_grouping',
            name='grouping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.grouping'),
        ),
        migrations.AddField(
            model_name='user_grouping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grouping',
            name='members',
            field=models.ManyToManyField(through='accounts.User_Grouping', to=settings.AUTH_USER_MODEL),
        ),
    ]
