# Generated by Django 5.1.7 on 2025-03-15 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouping',
            name='members',
        ),
        migrations.AddField(
            model_name='user',
            name='grouping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.grouping'),
        ),
        migrations.DeleteModel(
            name='User_Grouping',
        ),
    ]
