# Generated by Django 5.1.7 on 2025-03-19 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_grouping_members_user_grouping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grouping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.grouping'),
        ),
    ]
