# Generated by Django 5.1.7 on 2025-03-16 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_taskstatus_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creator_employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_creator', to='companies.employee'),
            preserve_default=False,
        ),
    ]
