# Generated by Django 5.1.7 on 2025-03-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_task_creator_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('1', 'Não iniciado'), ('2', 'Em andamento'), ('3', 'Feito')], max_length=1),
        ),
    ]
